// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       // return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         // return android;
//       case TargetPlatform.iOS:
//         // return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   // static const FirebaseOptions web = FirebaseOptions(
//   //   apiKey: 'AIzaSyBbmch_HOvL4f5ZZbFaIn11vFl_h2qtiis',
//   //   appId: '1:13082506823:web:249dd3fff7205097126362',
//   //   messagingSenderId: '13082506823',
//   //   projectId: 'mosti-template',
//   //   authDomain: 'mosti-template.firebaseapp.com',
//   //   storageBucket: 'mosti-template.appspot.com',
//   //   measurementId: 'G-B7ND88P7DV',
//   // );
//   //
//   // static const FirebaseOptions android = FirebaseOptions(
//   //   apiKey: 'AIzaSyCA2o3KtRlrM6zH0gx3As7Vyq_2yljQog8',
//   //   appId: '1:13082506823:android:a0988e57edcca1ed126362',
//   //   messagingSenderId: '13082506823',
//   //   projectId: 'mosti-template',
//   //   storageBucket: 'mosti-template.appspot.com',
//   // );
//   //
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyAm1q-jsGwH7dl6EXYHGuRl7HLMCjpDVKc',
//   //   appId: '1:13082506823:ios:ac1c11eeebc2a2cd126362',
//   //   messagingSenderId: '13082506823',
//   //   projectId: 'mosti-template',
//   //   storageBucket: 'mosti-template.appspot.com',
//   //   iosClientId: '13082506823-84vtja62aumnocb0u3p19dsvd4rib1s9.apps.googleusercontent.com',
//   //   iosBundleId: 'com.mrblab.travelhourapp',
//   // );
// }
